// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;
using Microsoft.CodeAnalysis;

namespace Roslynator.Formatting.CSharp
{
    public static partial class AnalyzerOptionDiagnosticRules
    {
        /// <summary>RCS0011i</summary>
        public static readonly DiagnosticDescriptor RemoveEmptyLineBetweenSingleLineAccessors = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionDiagnosticIdentifiers.RemoveEmptyLineBetweenSingleLineAccessors, 
            title:              "Remove empty line between single-line accessors.", 
            messageFormat:      "Remove empty line between single-line accessors.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionDiagnosticIdentifiers.RemoveEmptyLineBetweenSingleLineAccessors, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS0015i</summary>
        public static readonly DiagnosticDescriptor RemoveEmptyLineBetweenUsingDirectivesWithDifferentRootNamespace = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionDiagnosticIdentifiers.RemoveEmptyLineBetweenUsingDirectivesWithDifferentRootNamespace, 
            title:              "Remove empty line between using directives with different root namespace.", 
            messageFormat:      "Remove empty line between using directives with different root namespace.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionDiagnosticIdentifiers.RemoveEmptyLineBetweenUsingDirectivesWithDifferentRootNamespace, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS0027i</summary>
        public static readonly DiagnosticDescriptor AddNewLineAfterBinaryOperatorInsteadOfBeforeIt = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterBinaryOperatorInsteadOfBeforeIt, 
            title:              "Add newline after binary operator instead of before it.", 
            messageFormat:      "Add newline after binary operator instead of before it.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterBinaryOperatorInsteadOfBeforeIt, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS0028i</summary>
        public static readonly DiagnosticDescriptor AddNewLineAfterConditionalOperatorInsteadOfBeforeIt = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterConditionalOperatorInsteadOfBeforeIt, 
            title:              "Add newline after conditional operator instead of before it.", 
            messageFormat:      "Add newline after conditional operator instead of before it.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterConditionalOperatorInsteadOfBeforeIt, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS0032i</summary>
        public static readonly DiagnosticDescriptor AddNewLineAfterExpressionBodyArrowInsteadOfBeforeIt = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterExpressionBodyArrowInsteadOfBeforeIt, 
            title:              "Add newline after expression-body arrow instead of before it.", 
            messageFormat:      "Add newline after expression-body arrow instead of before it.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterExpressionBodyArrowInsteadOfBeforeIt, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS0051i</summary>
        public static readonly DiagnosticDescriptor RemoveNewLineBetweenClosingBraceAndWhileKeyword = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionDiagnosticIdentifiers.RemoveNewLineBetweenClosingBraceAndWhileKeyword, 
            title:              "Remove newline between closing brace and 'while' keyword.", 
            messageFormat:      "Remove newline between closing brace and 'while' keyword.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionDiagnosticIdentifiers.RemoveNewLineBetweenClosingBraceAndWhileKeyword, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS0052i</summary>
        public static readonly DiagnosticDescriptor AddNewLineAfterEqualsSignInsteadOfBeforeIt = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterEqualsSignInsteadOfBeforeIt, 
            title:              "Add newline after equals sign instead of before it.", 
            messageFormat:      "Add newline after equals sign instead of before it.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionDiagnosticIdentifiers.AddNewLineAfterEqualsSignInsteadOfBeforeIt, 
            customTags:         Array.Empty<string>());

    }
}