// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.Formatting.CSharp
{
    public static partial class AnalyzerOptions
    {
        internal static readonly AnalyzerOptionDescriptor MaxLineLength = new AnalyzerOptionDescriptor(null, DiagnosticDescriptors.LineIsTooLong, "roslynator.max_line_length");
        internal static readonly AnalyzerOptionDescriptor RemoveEmptyLineBetweenSingleLineAccessors = new AnalyzerOptionDescriptor(AnalyzerOptionDiagnosticDescriptors.RemoveEmptyLineBetweenSingleLineAccessors, DiagnosticDescriptors.AddEmptyLineBetweenSingleLineAccessorsOrViceVersa, "roslynator.RCS0011.invert");
        internal static readonly AnalyzerOptionDescriptor RemoveEmptyLineBetweenUsingDirectivesWithDifferentRootNamespace = new AnalyzerOptionDescriptor(AnalyzerOptionDiagnosticDescriptors.RemoveEmptyLineBetweenUsingDirectivesWithDifferentRootNamespace, DiagnosticDescriptors.AddEmptyLineBetweenUsingDirectivesWithDifferentRootNamespaceOrViceVersa, "roslynator.RCS0015.invert");
        internal static readonly AnalyzerOptionDescriptor AddNewLineAfterBinaryOperatorInsteadOfBeforeIt = new AnalyzerOptionDescriptor(AnalyzerOptionDiagnosticDescriptors.AddNewLineAfterBinaryOperatorInsteadOfBeforeIt, DiagnosticDescriptors.AddNewLineBeforeBinaryOperatorInsteadOfAfterItOrViceVersa, "roslynator.RCS0027.invert");
        internal static readonly AnalyzerOptionDescriptor AddNewLineAfterConditionalOperatorInsteadOfBeforeIt = new AnalyzerOptionDescriptor(AnalyzerOptionDiagnosticDescriptors.AddNewLineAfterConditionalOperatorInsteadOfBeforeIt, DiagnosticDescriptors.AddNewLineBeforeConditionalOperatorInsteadOfAfterItOrViceVersa, "roslynator.RCS0028.invert");
        internal static readonly AnalyzerOptionDescriptor AddNewLineAfterExpressionBodyArrowInsteadOfBeforeIt = new AnalyzerOptionDescriptor(AnalyzerOptionDiagnosticDescriptors.AddNewLineAfterExpressionBodyArrowInsteadOfBeforeIt, DiagnosticDescriptors.AddNewLineBeforeExpressionBodyArrowInsteadOfAfterItOrViceVersa, "roslynator.RCS0032.invert");
        internal static readonly AnalyzerOptionDescriptor RemoveNewLineBetweenClosingBraceAndWhileKeyword = new AnalyzerOptionDescriptor(AnalyzerOptionDiagnosticDescriptors.RemoveNewLineBetweenClosingBraceAndWhileKeyword, DiagnosticDescriptors.AddNewLineBetweenClosingBraceAndWhileKeywordOrViceVersa, "roslynator.RCS0051.invert");
        internal static readonly AnalyzerOptionDescriptor AddNewLineAfterEqualsSignInsteadOfBeforeIt = new AnalyzerOptionDescriptor(AnalyzerOptionDiagnosticDescriptors.AddNewLineAfterEqualsSignInsteadOfBeforeIt, DiagnosticDescriptors.AddNewLineBeforeEqualsSignInsteadOfAfterItOrViceVersa, "roslynator.RCS0052.invert");
    }
}