// Copyright (c) .NET Foundation and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;
using Microsoft.CodeAnalysis;

namespace Roslynator.Formatting.CSharp
{
    public static partial class DiagnosticRules
    {
        /// <summary>RCS0001</summary>
        public static readonly DiagnosticDescriptor AddBlankLineAfterEmbeddedStatement = DiagnosticDescriptors.RCS0001_AddBlankLineAfterEmbeddedStatement;

        /// <summary>RCS0002</summary>
        public static readonly DiagnosticDescriptor AddBlankLineAfterRegionDirective = DiagnosticDescriptors.RCS0002_AddBlankLineAfterRegionDirective;

        /// <summary>RCS0003</summary>
        public static readonly DiagnosticDescriptor AddBlankLineAfterUsingDirectiveList = DiagnosticDescriptors.RCS0003_AddBlankLineAfterUsingDirectiveList;

        /// <summary>RCS0005</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBeforeEndRegionDirective = DiagnosticDescriptors.RCS0005_AddBlankLineBeforeEndRegionDirective;

        /// <summary>RCS0006</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBeforeUsingDirectiveList = DiagnosticDescriptors.RCS0006_AddBlankLineBeforeUsingDirectiveList;

        /// <summary>RCS0007</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBetweenAccessors = DiagnosticDescriptors.RCS0007_AddBlankLineBetweenAccessors;

        /// <summary>RCS0008</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBetweenClosingBraceAndNextStatement = DiagnosticDescriptors.RCS0008_AddBlankLineBetweenClosingBraceAndNextStatement;

        /// <summary>RCS0009</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBetweenDeclarationAndDocumentationComment = DiagnosticDescriptors.RCS0009_AddBlankLineBetweenDeclarationAndDocumentationComment;

        /// <summary>RCS0010</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBetweenDeclarations = DiagnosticDescriptors.RCS0010_AddBlankLineBetweenDeclarations;

        /// <summary>RCS0011</summary>
        public static readonly DiagnosticDescriptor BlankLineBetweenSingleLineAccessors = DiagnosticDescriptors.RCS0011_BlankLineBetweenSingleLineAccessors;

        /// <summary>RCS0012</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBetweenSingleLineDeclarations = DiagnosticDescriptors.RCS0012_AddBlankLineBetweenSingleLineDeclarations;

        /// <summary>RCS0013</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBetweenSingleLineDeclarationsOfDifferentKind = DiagnosticDescriptors.RCS0013_AddBlankLineBetweenSingleLineDeclarationsOfDifferentKind;

        /// <summary>RCS0014</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBetweenSwitchSections = DiagnosticDescriptors.RCS0014_AddBlankLineBetweenSwitchSections;

        /// <summary>RCS0015</summary>
        public static readonly DiagnosticDescriptor BlankLineBetweenUsingDirectives = DiagnosticDescriptors.RCS0015_BlankLineBetweenUsingDirectives;

        /// <summary>RCS0016</summary>
        public static readonly DiagnosticDescriptor PutAttributeListOnItsOwnLine = DiagnosticDescriptors.RCS0016_PutAttributeListOnItsOwnLine;

        /// <summary>RCS0020</summary>
        public static readonly DiagnosticDescriptor FormatAccessorBraces = DiagnosticDescriptors.RCS0020_FormatAccessorBraces;

        /// <summary>RCS0021</summary>
        public static readonly DiagnosticDescriptor FormatBlockBraces = DiagnosticDescriptors.RCS0021_FormatBlockBraces;

        /// <summary>RCS0022</summary>
        public static readonly DiagnosticDescriptor AddNewLineAfterOpeningBraceOfEmptyBlock = DiagnosticDescriptors.RCS0022_AddNewLineAfterOpeningBraceOfEmptyBlock;

        /// <summary>RCS0023</summary>
        public static readonly DiagnosticDescriptor FormatTypeDeclarationBraces = DiagnosticDescriptors.RCS0023_FormatTypeDeclarationBraces;

        /// <summary>RCS0024</summary>
        public static readonly DiagnosticDescriptor AddNewLineAfterSwitchLabel = DiagnosticDescriptors.RCS0024_AddNewLineAfterSwitchLabel;

        /// <summary>RCS0025</summary>
        public static readonly DiagnosticDescriptor PutFullAccessorOnItsOwnLine = DiagnosticDescriptors.RCS0025_PutFullAccessorOnItsOwnLine;

        /// <summary>RCS0027</summary>
        public static readonly DiagnosticDescriptor PlaceNewLineAfterOrBeforeBinaryOperator = DiagnosticDescriptors.RCS0027_PlaceNewLineAfterOrBeforeBinaryOperator;

        /// <summary>RCS0028</summary>
        public static readonly DiagnosticDescriptor PlaceNewLineAfterOrBeforeConditionalOperator = DiagnosticDescriptors.RCS0028_PlaceNewLineAfterOrBeforeConditionalOperator;

        /// <summary>RCS0029</summary>
        public static readonly DiagnosticDescriptor PutConstructorInitializerOnItsOwnLine = DiagnosticDescriptors.RCS0029_PutConstructorInitializerOnItsOwnLine;

        /// <summary>RCS0030</summary>
        public static readonly DiagnosticDescriptor PutEmbeddedStatementOnItsOwnLine = DiagnosticDescriptors.RCS0030_PutEmbeddedStatementOnItsOwnLine;

        /// <summary>RCS0031</summary>
        public static readonly DiagnosticDescriptor PutEnumMemberOnItsOwnLine = DiagnosticDescriptors.RCS0031_PutEnumMemberOnItsOwnLine;

        /// <summary>RCS0032</summary>
        public static readonly DiagnosticDescriptor PlaceNewLineAfterOrBeforeArrowToken = DiagnosticDescriptors.RCS0032_PlaceNewLineAfterOrBeforeArrowToken;

        /// <summary>RCS0033</summary>
        public static readonly DiagnosticDescriptor PutStatementOnItsOwnLine = DiagnosticDescriptors.RCS0033_PutStatementOnItsOwnLine;

        /// <summary>RCS0034</summary>
        public static readonly DiagnosticDescriptor PutTypeParameterConstraintOnItsOwnLine = DiagnosticDescriptors.RCS0034_PutTypeParameterConstraintOnItsOwnLine;

        /// <summary>RCS0036</summary>
        public static readonly DiagnosticDescriptor RemoveBlankLineBetweenSingleLineDeclarationsOfSameKind = DiagnosticDescriptors.RCS0036_RemoveBlankLineBetweenSingleLineDeclarationsOfSameKind;

        /// <summary>RCS0038</summary>
        public static readonly DiagnosticDescriptor RemoveBlankLineBetweenUsingDirectivesWithSameRootNamespace = DiagnosticDescriptors.RCS0038_RemoveBlankLineBetweenUsingDirectivesWithSameRootNamespace;

        /// <summary>RCS0039</summary>
        public static readonly DiagnosticDescriptor RemoveNewLineBeforeBaseList = DiagnosticDescriptors.RCS0039_RemoveNewLineBeforeBaseList;

        /// <summary>RCS0041</summary>
        public static readonly DiagnosticDescriptor RemoveNewLineBetweenIfKeywordAndElseKeyword = DiagnosticDescriptors.RCS0041_RemoveNewLineBetweenIfKeywordAndElseKeyword;

        /// <summary>RCS0042</summary>
        public static readonly DiagnosticDescriptor PutAutoAccessorsOnSingleLine = DiagnosticDescriptors.RCS0042_PutAutoAccessorsOnSingleLine;

        /// <summary>RCS0043</summary>
        public static readonly DiagnosticDescriptor FormatAccessorBracesOnSingleLineWhenExpressionIsOnSingleLine = DiagnosticDescriptors.RCS0043_FormatAccessorBracesOnSingleLineWhenExpressionIsOnSingleLine;

        /// <summary>RCS0044</summary>
        public static readonly DiagnosticDescriptor UseCarriageReturnAndLinefeedAsNewLine = DiagnosticDescriptors.RCS0044_UseCarriageReturnAndLinefeedAsNewLine;

        /// <summary>RCS0045</summary>
        public static readonly DiagnosticDescriptor UseLinefeedAsNewLine = DiagnosticDescriptors.RCS0045_UseLinefeedAsNewLine;

        /// <summary>RCS0046</summary>
        public static readonly DiagnosticDescriptor UseSpacesInsteadOfTab = DiagnosticDescriptors.RCS0046_UseSpacesInsteadOfTab;

        /// <summary>RCS0047</summary>
        public static readonly DiagnosticDescriptor WrapAndIndentEachNodeInList = DiagnosticDescriptors.RCS0047_WrapAndIndentEachNodeInList;

        /// <summary>RCS0048</summary>
        public static readonly DiagnosticDescriptor PutInitializerOnSingleLine = DiagnosticDescriptors.RCS0048_PutInitializerOnSingleLine;

        /// <summary>RCS0049</summary>
        public static readonly DiagnosticDescriptor AddBlankLineAfterTopComment = DiagnosticDescriptors.RCS0049_AddBlankLineAfterTopComment;

        /// <summary>RCS0050</summary>
        public static readonly DiagnosticDescriptor AddBlankLineBeforeTopDeclaration = DiagnosticDescriptors.RCS0050_AddBlankLineBeforeTopDeclaration;

        /// <summary>RCS0051</summary>
        public static readonly DiagnosticDescriptor AddOrRemoveNewLineBeforeWhileInDoStatement = DiagnosticDescriptors.RCS0051_AddOrRemoveNewLineBeforeWhileInDoStatement;

        /// <summary>RCS0052</summary>
        public static readonly DiagnosticDescriptor PlaceNewLineAfterOrBeforeEqualsToken = DiagnosticDescriptors.RCS0052_PlaceNewLineAfterOrBeforeEqualsToken;

        /// <summary>RCS0053</summary>
        public static readonly DiagnosticDescriptor FixFormattingOfList = DiagnosticDescriptors.RCS0053_FixFormattingOfList;

        /// <summary>RCS0054</summary>
        public static readonly DiagnosticDescriptor FixFormattingOfCallChain = DiagnosticDescriptors.RCS0054_FixFormattingOfCallChain;

        /// <summary>RCS0055</summary>
        public static readonly DiagnosticDescriptor FixFormattingOfBinaryExpressionChain = DiagnosticDescriptors.RCS0055_FixFormattingOfBinaryExpressionChain;

        /// <summary>RCS0056</summary>
        public static readonly DiagnosticDescriptor LineIsTooLong = DiagnosticDescriptors.RCS0056_LineIsTooLong;

        /// <summary>RCS0057</summary>
        public static readonly DiagnosticDescriptor NormalizeWhitespaceAtBeginningOfFile = DiagnosticDescriptors.RCS0057_NormalizeWhitespaceAtBeginningOfFile;

        /// <summary>RCS0058</summary>
        public static readonly DiagnosticDescriptor NormalizeWhitespaceAtEndOfFile = DiagnosticDescriptors.RCS0058_NormalizeWhitespaceAtEndOfFile;

        /// <summary>RCS0059</summary>
        public static readonly DiagnosticDescriptor PlaceNewLineAfterOrBeforeNullConditionalOperator = DiagnosticDescriptors.RCS0059_PlaceNewLineAfterOrBeforeNullConditionalOperator;

        /// <summary>RCS0060</summary>
        public static readonly DiagnosticDescriptor BlankLineAfterFileScopedNamespaceDeclaration = DiagnosticDescriptors.RCS0060_BlankLineAfterFileScopedNamespaceDeclaration;

        /// <summary>RCS0061</summary>
        public static readonly DiagnosticDescriptor BlankLineBetweenSwitchSections = DiagnosticDescriptors.RCS0061_BlankLineBetweenSwitchSections;

    }
}