// Copyright (c) .NET Foundation and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;
using Microsoft.CodeAnalysis;

namespace Roslynator.CodeAnalysis.CSharp
{
    public static partial class DiagnosticRules
    {
        /// <summary>RCS9001</summary>
        public static readonly DiagnosticDescriptor UsePatternMatching = DiagnosticDescriptors.RCS9001_UsePatternMatching;

        /// <summary>RCS9002</summary>
        public static readonly DiagnosticDescriptor UsePropertySyntaxNodeSpanStart = DiagnosticDescriptors.RCS9002_UsePropertySyntaxNodeSpanStart;

        /// <summary>RCS9003</summary>
        public static readonly DiagnosticDescriptor UnnecessaryConditionalAccess = DiagnosticDescriptors.RCS9003_UnnecessaryConditionalAccess;

        public static readonly DiagnosticDescriptor UnnecessaryConditionalAccessFadeOut = DiagnosticDescriptorFactory.CreateFadeOut(UnnecessaryConditionalAccess);

        /// <summary>RCS9004</summary>
        public static readonly DiagnosticDescriptor CallAnyInsteadOfAccessingCount = DiagnosticDescriptors.RCS9004_CallAnyInsteadOfAccessingCount;

        /// <summary>RCS9005</summary>
        public static readonly DiagnosticDescriptor UnnecessaryNullCheck = DiagnosticDescriptors.RCS9005_UnnecessaryNullCheck;

        /// <summary>RCS9006</summary>
        public static readonly DiagnosticDescriptor UseElementAccess = DiagnosticDescriptors.RCS9006_UseElementAccess;

        /// <summary>RCS9007</summary>
        public static readonly DiagnosticDescriptor UseReturnValue = DiagnosticDescriptors.RCS9007_UseReturnValue;

        /// <summary>RCS9008</summary>
        public static readonly DiagnosticDescriptor CallLastInsteadOfUsingElementAccess = DiagnosticDescriptors.RCS9008_CallLastInsteadOfUsingElementAccess;

        /// <summary>RCS9009</summary>
        public static readonly DiagnosticDescriptor UnknownLanguageName = DiagnosticDescriptors.RCS9009_UnknownLanguageName;

        /// <summary>RCS9010</summary>
        public static readonly DiagnosticDescriptor SpecifyExportCodeRefactoringProviderAttributeName = DiagnosticDescriptors.RCS9010_SpecifyExportCodeRefactoringProviderAttributeName;

        /// <summary>RCS9011</summary>
        public static readonly DiagnosticDescriptor SpecifyExportCodeFixProviderAttributeName = DiagnosticDescriptors.RCS9011_SpecifyExportCodeFixProviderAttributeName;

    }
}