// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;
using Microsoft.CodeAnalysis;

namespace Roslynator.CSharp
{
    public static partial class AnalyzerOptions
    {
        /// <summary>RCS1018i</summary>
        public static readonly DiagnosticDescriptor RemoveAccessibilityModifiers = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.RemoveAccessibilityModifiers, 
            title:              "Remove accessibility modifiers.", 
            messageFormat:      "Remove accessibility modifiers.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.RemoveAccessibilityModifiers, 
            customTags:         WellKnownDiagnosticTags.Unnecessary);

        /// <summary>RCS1036a</summary>
        public static readonly DiagnosticDescriptor RemoveEmptyLineBetweenClosingBraceAndSwitchSection = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.RemoveEmptyLineBetweenClosingBraceAndSwitchSection, 
            title:              "Remove empty line between closing brace and switch section.", 
            messageFormat:      "Remove empty line between closing brace and switch section.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.RemoveEmptyLineBetweenClosingBraceAndSwitchSection, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1045a</summary>
        public static readonly DiagnosticDescriptor DoNotRenamePrivateStaticReadOnlyFieldToCamelCaseWithUnderscore = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.DoNotRenamePrivateStaticReadOnlyFieldToCamelCaseWithUnderscore, 
            title:              "Do not rename private static read-only field to camel case with underscore.", 
            messageFormat:      "Do not rename private static read-only field to camel case with underscore.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.DoNotRenamePrivateStaticReadOnlyFieldToCamelCaseWithUnderscore, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1050i</summary>
        public static readonly DiagnosticDescriptor RemoveArgumentListFromObjectCreation = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.RemoveArgumentListFromObjectCreation, 
            title:              "Remove argument list from object creation expression.", 
            messageFormat:      "Remove argument list from object creation expression.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.RemoveArgumentListFromObjectCreation, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1051a</summary>
        public static readonly DiagnosticDescriptor RemoveParenthesesFromConditionOfConditionalExpressionWhenExpressionIsSingleToken = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.RemoveParenthesesFromConditionOfConditionalExpressionWhenExpressionIsSingleToken, 
            title:              "Remove parentheses from condition of conditional expression (when condition is a single token).", 
            messageFormat:      "Remove parentheses from condition of conditional expression (when condition is a single token).", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.RemoveParenthesesFromConditionOfConditionalExpressionWhenExpressionIsSingleToken, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1096i</summary>
        public static readonly DiagnosticDescriptor ConvertBitwiseOperationToHasFlagCall = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.ConvertBitwiseOperationToHasFlagCall, 
            title:              "Convert bitwise operation to 'HasFlag' call.", 
            messageFormat:      "Convert bitwise operation to 'HasFlag' call.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.ConvertBitwiseOperationToHasFlagCall, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1104a</summary>
        public static readonly DiagnosticDescriptor SimplifyConditionalExpressionWhenItIncludesNegationOfCondition = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.SimplifyConditionalExpressionWhenItIncludesNegationOfCondition, 
            title:              "Simplify conditional expression (when it includes negation of condition).", 
            messageFormat:      "Simplify conditional expression (when it includes negation of condition).", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.SimplifyConditionalExpressionWhenItIncludesNegationOfCondition, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1207i</summary>
        public static readonly DiagnosticDescriptor ConvertMethodGroupToAnonymousFunction = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.ConvertMethodGroupToAnonymousFunction, 
            title:              "Convert method group to anonymous function.", 
            messageFormat:      "Convert method group to anonymous function.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Hidden, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.ConvertMethodGroupToAnonymousFunction, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1246a</summary>
        public static readonly DiagnosticDescriptor DoNotUseElementAccessWhenExpressionIsInvocation = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.DoNotUseElementAccessWhenExpressionIsInvocation, 
            title:              "Do not use element access when expression is invocation.", 
            messageFormat:      "Do not use element access when expression is invocation.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.DoNotUseElementAccessWhenExpressionIsInvocation, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1248a</summary>
        public static readonly DiagnosticDescriptor UseIsNullPatternInsteadOfInequalityOperator = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.UseIsNullPatternInsteadOfInequalityOperator, 
            title:              "Use 'is null' pattern instead of '!=' operator.", 
            messageFormat:      "Use 'is null' pattern instead of '!=' operator.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.UseIsNullPatternInsteadOfInequalityOperator, 
            customTags:         Array.Empty<string>());

        /// <summary>RCS1248i</summary>
        public static readonly DiagnosticDescriptor UseComparisonInsteadOfIsNullPattern = DiagnosticDescriptorFactory.Default.Create(
            id:                 AnalyzerOptionIdentifiers.UseComparisonInsteadOfIsNullPattern, 
            title:              "Use comparison instead of 'is null' pattern.", 
            messageFormat:      "Use comparison instead of 'is null' pattern.", 
            category:           DiagnosticCategories.AnalyzerOption, 
            defaultSeverity:    DiagnosticSeverity.Info, 
            isEnabledByDefault: false, 
            description:        null, 
            helpLinkUri:        AnalyzerOptionIdentifiers.UseComparisonInsteadOfIsNullPattern, 
            customTags:         Array.Empty<string>());

    }
}