// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.ConstructorInitializerSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.CrefSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.OrderingSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.SelectOrGroupClauseSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetTypeSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ITypeSymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetTypeSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.ConstructorInitializerSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ITypeSymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetTypeSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ITypeSymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1196:Call extension method as instance method.", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.CSharpExtensions.GetTypeSymbol(Microsoft.CodeAnalysis.SemanticModel,Microsoft.CodeAnalysis.CSharp.Syntax.SelectOrGroupClauseSyntax,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.ITypeSymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.IfStatementCascade.op_Equality(Roslynator.CSharp.IfStatementCascade,Roslynator.CSharp.IfStatementCascade)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:Roslynator.CSharp.IfStatementCascade.op_Inequality(Roslynator.CSharp.IfStatementCascade,Roslynator.CSharp.IfStatementCascade)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.AsExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.AssignmentExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.BinaryExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.ConditionalExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.GenericInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.IsExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.LocalDeclarationStatementInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.MemberDeclarationListInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.ModifierListInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.NullCheckExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.RegionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.SimpleAssignmentExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.SimpleAssignmentStatementInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.SimpleIfStatementInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.SimpleMemberInvocationExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.SimpleMemberInvocationStatementInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.SingleLocalDeclarationStatementInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.SingleParameterLambdaExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.StatementListInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.StringConcatenationExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.StringLiteralExpressionInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.UsingDirectiveListInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "<Pending>", Scope = "type", Target = "~T:Roslynator.CSharp.Syntax.XmlElementInfo")]

