blank_issues_enabled: false
contact_links:
  - name: Contributing guide
    url: https://github.com/dotnet/roslynator/blob/main/CONTRIBUTING.md
    about: Read issue and PR guidelines before opening a ticket.
