// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;

namespace Roslynator.Documentation
{
    [Flags]
    public enum DeclarationListParts
    {
        None = 0,
        AutoGeneratedComment = 1,
        AssemblyAttributes = 2,
        All = AutoGeneratedComment | AssemblyAttributes,
    }
}
