// Copyright (c) Josef Pihrt and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using Roslynator.CSharp;

namespace Roslynator.VisualStudio
{
    public partial class CodeFixesOptionsPage
    {
    }
}