// Copyright (c) Josef Pihrt and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator
{
    public static class ConfigOptions
    {
        public static readonly ConfigOptionDescriptor MaxLineLength = new(key: ConfigOptionKeys.MaxLineLength, defaultValue: "140", description: "Max line length", valuePlaceholder: "<MAX_LINE_LENGTH>");
        public static readonly ConfigOptionDescriptor PreferNoNewLineAtEndOfFile = new(key: ConfigOptionKeys.PreferNoNewLineAtEndOfFile, defaultValue: "false", description: "Prefer no new line at the end of a file", valuePlaceholder: "true|false");
        public static readonly ConfigOptionDescriptor PrefixFieldIdentifierWithUnderscore = new(key: ConfigOptionKeys.PrefixFieldIdentifierWithUnderscore, defaultValue: "false", description: "Prefix field identifier with underscore", valuePlaceholder: "true|false");
    }
}