// Copyright (c) Josef Pihrt and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator
{
    internal static partial class ConfigOptionValues
    {
        public const string AccessibilityModifiers_Explicit                                             = "explicit";
        public const string AccessibilityModifiers_Implicit                                             = "implicit";
        public const string AccessorBracesStyle_MultiLine                                               = "multi_line";
        public const string AccessorBracesStyle_SingleLineWhenExpressionIsOnSingleLine                  = "single_line_when_expression_is_on_single_line";
        public const string ArrayCreationTypeStyle_Explicit                                             = "explicit";
        public const string ArrayCreationTypeStyle_Implicit                                             = "implicit";
        public const string ArrayCreationTypeStyle_ImplicitWhenTypeIsObvious                            = "implicit_when_type_is_obvious";
        public const string ArrowTokenNewLine_After                                                     = "after";
        public const string ArrowTokenNewLine_Before                                                    = "before";
        public const string BinaryOperatorNewLine_After                                                 = "after";
        public const string BinaryOperatorNewLine_Before                                                = "before";
        public const string BlankLineBetweenUsingDirectives_Never                                       = "never";
        public const string BlankLineBetweenUsingDirectives_SeparateGroups                              = "separate_groups";
        public const string BlockBracesStyle_MultiLine                                                  = "multi_line";
        public const string BlockBracesStyle_SingleLineWhenEmpty                                        = "single_line_when_empty";
        public const string BodyStyle_Block                                                             = "block";
        public const string BodyStyle_Expression                                                        = "expression";
        public const string ConditionalOperatorConditionParenthesesStyle_Include                        = "include";
        public const string ConditionalOperatorConditionParenthesesStyle_Omit                           = "omit";
        public const string ConditionalOperatorConditionParenthesesStyle_OmitWhenConditionIsSingleToken = "omit_when_condition_is_single_token";
        public const string ConditionalOperatorNewLine_After                                            = "after";
        public const string ConditionalOperatorNewLine_Before                                           = "before";
        public const string EmptyStringStyle_Field                                                      = "field";
        public const string EmptyStringStyle_Literal                                                    = "literal";
        public const string EnumHasFlagStyle_Method                                                     = "method";
        public const string EnumHasFlagStyle_Operator                                                   = "operator";
        public const string EqualsTokenNewLine_After                                                    = "after";
        public const string EqualsTokenNewLine_Before                                                   = "before";
        public const string NullConditionalOperatorNewLine_After                                        = "after";
        public const string NullConditionalOperatorNewLine_Before                                       = "before";
        public const string NullCheckStyle_EqualityOperator                                             = "equality_operator";
        public const string NullCheckStyle_PatternMatching                                              = "pattern_matching";
        public const string ObjectCreationParenthesesStyle_Include                                      = "include";
        public const string ObjectCreationParenthesesStyle_Omit                                         = "omit";
        public const string ObjectCreationTypeStyle_Explicit                                            = "explicit";
        public const string ObjectCreationTypeStyle_Implicit                                            = "implicit";
        public const string ObjectCreationTypeStyle_ImplicitWhenTypeIsObvious                           = "implicit_when_type_is_obvious";
        public const string UseAnonymousFunctionOrMethodGroup_AnonymousFunction                         = "anonymous_function";
        public const string UseAnonymousFunctionOrMethodGroup_MethodGroup                               = "method_group";
    }
}